spring:
  datasource:
    url: jdbc:mysql://localhost/egg_upms_db
    username: egg_upms
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    org.springframework: debug