DROP TABLE IF EXISTS UPMS_ACCOUNT;
CREATE TABLE UPMS_ACCOUNT(
    ACCOUNT_ID INT NOT NULL AUTO_INCREMENT  COMMENT '账户ID' ,
    ACCOUNT_TYPE VARCHAR(255)    COMMENT '账户类型，个人/..' ,
    USERNAME VARCHAR(255) NOT NULL   COMMENT '用户名(登陆名)' ,
    PASSWORD VARCHAR(255) NOT NULL   COMMENT '密码' ,
    STATUS VARCHAR(32) NOT NULL   COMMENT '状态' ,
    TENANT_ID VARCHAR(32)    COMMENT '租户号' ,
    REVISION VARCHAR(32)    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ACCOUNT_ID)
)  COMMENT = '账户';

DROP TABLE IF EXISTS UPMS_PERSON;
CREATE TABLE UPMS_PERSON(
    PERSON_ID INT NOT NULL AUTO_INCREMENT  COMMENT 'ID' ,
    FIRST_NAME VARCHAR(255) NOT NULL   COMMENT '名字' ,
    LAST_NAME VARCHAR(255) NOT NULL   COMMENT '姓' ,
    ID_TYPE VARCHAR(32)    COMMENT '证件类型' ,
    ID_NUMBER VARCHAR(255)    COMMENT '证件号' ,
    STATUS VARCHAR(255) NOT NULL   COMMENT '状态' ,
    TENANT_ID VARCHAR(32)    COMMENT '租户号' ,
    REVISION VARCHAR(32)    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(255)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (PERSON_ID)
)  COMMENT = '个人信息';


CREATE UNIQUE INDEX ID_TYPE_NUMBER_UNIQUE ON UPMS_PERSON(ID_TYPE,ID_NUMBER);

DROP TABLE IF EXISTS PERSON_ACCOUNT_RELATION;
CREATE TABLE PERSON_ACCOUNT_RELATION(
    ID INT NOT NULL AUTO_INCREMENT  COMMENT 'ID' ,
    PERSION_ID INT NOT NULL   COMMENT '个人信息表ID' ,
    ACCOUNT_ID INT NOT NULL   COMMENT '账户id' ,
    STATUS VARCHAR(255) NOT NULL   COMMENT '状态' ,
    TENANT_ID VARCHAR(32)    COMMENT '租户号' ,
    REVISION VARCHAR(32)    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
)  COMMENT = '个人信息账户关系表';

DROP TABLE IF EXISTS UPMS_CONTACT;
CREATE TABLE UPMS_CONTACT(
    CONTACT_ID INT NOT NULL AUTO_INCREMENT  COMMENT 'id' ,
    CONTACT_TYPE VARCHAR(32) NOT NULL   COMMENT '联系方式(手机/邮箱/地址)' ,
    CONTACT_INFO VARCHAR(255) NOT NULL   COMMENT '联系信息' ,
    PERSON_ID INT NOT NULL   COMMENT '个人信息ID' ,
    IS_ PRIMARY VARCHAR(1) NOT NULL   COMMENT '首选联系方式，Y/N' ,
    STATUS VARCHAR(255) NOT NULL   COMMENT '状态' ,
    TENANT_ID VARCHAR(32)    COMMENT '租户号' ,
    REVISION VARCHAR(32)    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (CONTACT_ID)
)  COMMENT = '联系方式';

DROP TABLE IF EXISTS UPMS_ROLE;
CREATE TABLE UPMS_ROLE(
    ROLE_ID INT NOT NULL AUTO_INCREMENT  COMMENT 'ID' ,
    ROLE_CODE VARCHAR(255) NOT NULL   COMMENT '角色码' ,
    ROLE_NAME VARCHAR(255) NOT NULL   COMMENT '角色名称' ,
    STATUS VARCHAR(255) NOT NULL   COMMENT '状态' ,
    TENANT_ID VARCHAR(32)    COMMENT '租户号' ,
    REVISION VARCHAR(32)    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ROLE_ID)
)  COMMENT = '账户角色信息';


CREATE UNIQUE INDEX ROLE_CODE_UNIQUE ON UPMS_ROLE(ROLE_CODE);

DROP TABLE IF EXISTS UPMS_ACCOUNT_ROLE_RELATION;
CREATE TABLE UPMS_ACCOUNT_ROLE_RELATION(
    ID INT NOT NULL AUTO_INCREMENT  COMMENT 'ID' ,
    ACCOUNT_ID INT NOT NULL   COMMENT '账户ID' ,
    ROLE_ID INT NOT NULL   COMMENT '角色ID' ,
    STATUS VARCHAR(255) NOT NULL   COMMENT '状态' ,
    TENANT_ID VARCHAR(32)    COMMENT '租户号' ,
    REVISION VARCHAR(32)    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
)  COMMENT = '账户角色关系';

DROP TABLE IF EXISTS UMPS_RESOURCE;
CREATE TABLE UMPS_RESOURCE(
    RESOURCE_ID INT NOT NULL AUTO_INCREMENT  COMMENT 'ID' ,
    RESOURCE_TYPE VARCHAR(255) NOT NULL   COMMENT '资源类型，系统/菜单/按键/链接' ,
    RESOURCE_URL VARCHAR(255) NOT NULL   COMMENT '资源链接' ,
    RESOURCE_NAME VARCHAR(255) NOT NULL   COMMENT '资源名称' ,
    RESOURCE_DESCRIPTION VARCHAR(255)    COMMENT '资源描述' ,
    STATUS VARCHAR(255) NOT NULL   COMMENT '状态' ,
    TENANT_ID VARCHAR(32)    COMMENT '租户号' ,
    REVISION VARCHAR(32)    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (RESOURCE_ID)
)  COMMENT = '资源(系统/菜单/按键/链接)';

DROP TABLE IF EXISTS UPMS_ROLE_RESOURCE_RELATION;
CREATE TABLE UPMS_ROLE_RESOURCE_RELATION(
    ID INT NOT NULL AUTO_INCREMENT  COMMENT 'id' ,
    ROLE_ID INT NOT NULL   COMMENT '角色id' ,
    RESOURCE_ID INT NOT NULL   COMMENT '资源id' ,
    STATUS VARCHAR(255)    COMMENT '状态' ,
    TENANT_ID VARCHAR(32)    COMMENT '租户号' ,
    REVISION VARCHAR(32)    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
)  COMMENT = '角色资源关系';

DROP TABLE IF EXISTS UPMS_ORGANIZATION;
CREATE TABLE UPMS_ORGANIZATION(
    ORGANIZATION_ID INT NOT NULL AUTO_INCREMENT  COMMENT 'ID' ,
    PARENT_ORGANIZATION_ID INT    COMMENT '上级机构ID' ,
    ORGANIZATION_CODE VARCHAR(255)    COMMENT '机构码' ,
    ORGANIZATION_TYPE VARCHAR(255)    COMMENT '机构类型，公司/部门' ,
    ORGANIZATION_NAME VARCHAR(255) NOT NULL   COMMENT '机构名称' ,
    ORGANIZATION_DESCRIPTION VARCHAR(255)    COMMENT '机构描述' ,
    ESTABLISHMENT_DATE DATETIME    COMMENT '成立时间' ,
    STATUS VARCHAR(255) NOT NULL   COMMENT '状态' ,
    TENANT_ID VARCHAR(32)    COMMENT '租户号' ,
    REVISION VARCHAR(32)    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ORGANIZATION_ID)
)  COMMENT = '组织';


CREATE UNIQUE INDEX ORGANIZATION_CODE_UNIQUE ON UPMS_ORGANIZATION(,);

DROP TABLE IF EXISTS UPMS_STATION;
CREATE TABLE UPMS_STATION(
    STATION_ID INT NOT NULL AUTO_INCREMENT  COMMENT 'ID' ,
    STATION_NAME VARCHAR(255) NOT NULL   COMMENT '岗位名称' ,
    STATION_DESCRIPTION VARCHAR(255)    COMMENT '岗位描述' ,
    STATION_LEVEL INT    COMMENT '岗位级别' ,
    STATUS VARCHAR(255) NOT NULL   COMMENT '状态' ,
    TENANT_ID VARCHAR(32)    COMMENT '租户号' ,
    REVISION VARCHAR(32)    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (STATION_ID)
)  COMMENT = '岗位';

DROP TABLE IF EXISTS UPMS_PERSON_ORGANIZATION_RELATION;
CREATE TABLE UPMS_PERSON_ORGANIZATION_RELATION(
    ID INT NOT NULL AUTO_INCREMENT  COMMENT 'ID' ,
    PERSON_ID INT NOT NULL   COMMENT '个人ID' ,
    ORGANIZATION_ID INT NOT NULL   COMMENT '机构ID' ,
    STATUS VARCHAR(255) NOT NULL   COMMENT '状态' ,
    TENANT_ID VARCHAR(32)    COMMENT '租户号' ,
    REVISION VARCHAR(32)    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
)  COMMENT = '个人机构关系';

DROP TABLE IF EXISTS UPMS_PERSON_STATION_RELATION;
CREATE TABLE UPMS_PERSON_STATION_RELATION(
    ID INT NOT NULL AUTO_INCREMENT  COMMENT 'ID' ,
    PERSON_ID INT NOT NULL   COMMENT '个人ID' ,
    STATION_ID INT NOT NULL   COMMENT '岗位ID' ,
    STATUS VARCHAR(255) NOT NULL   COMMENT '状态' ,
    TENANT_ID VARCHAR(32)    COMMENT '租户号' ,
    REVISION VARCHAR(32)    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
)  COMMENT = '个人岗位关系';

